### ISSUE TITLE
add "Copy decklist to clipboard"

### ISSUE THREAD

**Issue by mplain** [ThronesDB/thronesdb#130]
Throneteki, a browser-based platform for playing Thrones online, is getting popular.

Right now, in order to import a decklist from ThronesDB to Throneteki, one needs to press "Save as text file", open that text file, select all contents, and copy-paste it to Throneteki.

While not terribly hard to do, it involves several unnecessary steps, and, perhaps more importantly, it is more complicated when using a tablet.

I suggest adding to the "Save as" menu a new option to "Copy decklist to clipboard".  So that the whole decklist (card names, including set in parenthesis for unqiues with multiple versions, and the number of copies) would be copied straight to clipboard.

**Comment by mplain** [comment]
With throneteki being very popular currently, improving integration with thronesdb seems to be worthwhile.

**Comment by stopfstedt** [comment]
fixed via https://github.com/ThronesDB/thronesdb/pull/243
