### ISSUE TITLE
Separate plot decks for Rains of Castamere

### ISSUE THREAD

**Issue by mplain** [ThronesDB/thronesdb#133]
"The Rains of Castamere" agenda has special deckbuilding restrictions that effectively result in needing two separate plot decks: 7 non-Scheme plots and 5 Scheme plots.

It would be very useful to have them separated into two piles in the deckbuilder and deck view modes.

Suggested solution: if agenda = Rains then add a priority sorting method for Plot cards: non-Scheme plots first, then Scheme plots. Preferrably separate them by an empty space.

**Comment by Alsciende** [comment]
Yes, I guess that's a good and easy solution to the problem. I don't have the time to address the issue right now, but if someone wants to submit a PR, I'll consider it.

**Comment by itadakimas** [comment]
On octgn, there is a pile called the "Special Pile". Could it be used for this ?

**Comment by mplain** [comment]
Rains of Castamere is getting more popular across different factions, users are asking to implement this.
