### ISSUE TITLE
Allow sorting decklists by Set

### ISSUE THREAD

**Issue by techieAgnostic** [ThronesDB/thronesdb#146]
Give the option to sort decklists by set, so that we can easily see which card is from which set for people who store their collection in sets.

Netrunnerdb allows this already.

**Comment by KakitaShiro** [comment]
Yes, I asked about this a while ago as well. 
https://github.com/Alsciende/thronesdb/issues/96

**Comment by stopfstedt** [comment]
old ticket, this got fixed with the dec. 18 release.
