### ISSUE TITLE
Feature request: Additional languages

### ISSUE THREAD

**Issue by Landen13** [ThronesDB/thronesdb#161]
Is it possible to add additional translations (cards, rules, whole website)? How can users help dev team with this?

**Comment by fafranco82** [comment]
As one that added the Spanish translation to this site, yes, it's possible to add another language. Which language you want to add?

For website translation, some files (a very few) must be added, and then translate a file containing all string literals used in the web. Some static pages like rules reference need to be translated as well.

For card data, there is a repository here http://github.com/Alsciende/thronesdb-json-data that you can fork and clone, follow the instructions in `README` file to add another locale, edit the files generated and make a PR.

**Comment by Landen13** [comment]
@fafranco82 thnx for the answer! I wanna add russian translation. Will check out cards repo later, thnx.

In our russian community there are some cards translates already, but only related to the core. Also only "Learn to play" is translated, "Rules References" will take some time. I'll try to do this.

**Comment by mplain** [comment]
Are we adding unofficial, fan-made translations here?

**Comment by Alsciende** [comment]
Is it really an issue?

**Comment by mplain** [comment]
No, I guess it's not.

**Comment by stopfstedt** [comment]
we're not considering adding additional languages to thronesdb at the moment, since the application does not fully support it currently.
