### ISSUE TITLE
Deck builder does not remember selected sets

### ISSUE THREAD

**Issue by yads** [ThronesDB/thronesdb#202]
When I deselect available sets in the deckbuilder, thronesdb does not remember my selection next time I go in. I know this feature was available in netrunnerdb. Is it possible to add it to thronesdb? As someone who doesn't own the full card pool, it's somewhat frustrating to update the selections every time I use the deck builder.

**Comment by jyourstone** [comment]
+1, it would be great to have this.

Any update on whether or not this function will be added soon?

**Comment by stopfstedt** [comment]
hey guys, first time i'm actually giving this ticket some thought after taking over as maintainer.

so what i'm hearing is that you would like some sort of collection manager, which controls set (pre-)selection in the deck builder.
do i have this right so far?

there was a conversation about a collection manager in one of the FB groups recently, I filed a ticket on this as a reminder and future starting point for this feature. Seems related, please see here: 
https://github.com/ThronesDB/thronesdb/issues/330

as far as an ETA goes - it's not on the immediate development road map. i'll see if i can slot this in later this summer, feel free to ping me here if you don't hear anything back by August.

**Comment by jyourstone** [comment]
Hi,

Yes in the long run a collection manager like suggested in #330 would be even better.

But for now I would be happy just if the website could remember which sets I have selected. As it is now, every time I refresh the page, all sets get selected again.

**Comment by stopfstedt** [comment]
@jyourstone alright, that makes sense. i'll see if/how i can apply a band-aid in the way you're describing. will look into it next week.

**Comment by jyourstone** [comment]
That's much appreciated, thank you!

**Comment by stopfstedt** [comment]
quick update:
i took a peek at how netrunner db does it last night. 
and although i can't straight-up copy their solution into thronesdb (their frontend code has diverged quite a bit from ours), it still gave me a good-enough idea on how to go about it.
will have a stab at it over the 4th of july weekend.

**Comment by jyourstone** [comment]
Thank you! Looking forward to it.

**Comment by stopfstedt** [comment]
Ok, the code for this is in. I'll deploy later this month with alongside a few other changes. Will keep you posted here.

**Comment by jyourstone** [comment]
Great news! Thank you!

**Comment by stopfstedt** [comment]
Just deployed this to production. 

_Note_ In case that pack selections are _still_ not sticky when using the site next, then please purge your browser cache - the old javascript may still be hanging around.

**Comment by jyourstone** [comment]
It works like a charm!
This is perfect and will save everyone a lot of hassle. Thank you again!

**Comment by stopfstedt** [comment]
@jyourstone thanks for verifying and the feedback!
