### ISSUE TITLE
Limit 'Cards' menu list height

### ISSUE THREAD

**Issue by dimitrisnl** [ThronesDB/thronesdb#210]
Could possibly use something like:

```
max-height: 400px;
overflow: auto;
```

<img width="531" alt="screen shot 2018-09-15 at 23 06 39" src="https://user-images.githubusercontent.com/4951004/45590207-21bcd580-b93c-11e8-850f-50c5fc0a2541.png">

**Comment by dimitrisnl** [comment]
Can open a PR if this change is desirable @Alsciende

**Comment by stopfstedt** [comment]
@dimitrisnl yes please, throw us a PR! thanks.

**Comment by stopfstedt** [comment]
i'm yanking the whole dropdown.

superseded by #281
