### ISSUE TITLE
Restricted Lists validation and indicators

### ISSUE THREAD

**Issue by stopfstedt** [ThronesDB/thronesdb#247]
Currently, there are two restricted lists (RL) in effect for tournament play - one for the Melee format, and one for Joust.

Thronesdb needs indicate RL violations in the deck builder, the deck/decklist detail views, and in the "decklists" and "my decks" list views.

Out of scope are API changes, and search form additions (e.g. "exclude restristed lists").

We can start by using NetrunnerDB as a model for displaying RL compliance status:

![selection_241](https://user-images.githubusercontent.com/1410427/50568422-69f2de80-0d06-11e9-9e48-724d83f1bf1b.png)

**Comment by ystros** [comment]
For what it's worth, we already maintain the restricted list data:
https://github.com/throneteki/throneteki-json-data/blob/master/restricted-list.json

I'm not sure how that format compares to what was done with NetrunnerDB, but it's been enough for us to validate decks on Throneteki.
