### ISSUE TITLE
data importer: import directly from throneteki-json-data

### ISSUE THREAD

**Issue by stopfstedt** [ThronesDB/thronesdb#314]
rewrite the importer to ingest data from the thronesteki data repo. then, retire thronesdb-json-data.

**Comment by ystros** [comment]
Not sure whether it'll be helpful, but here's the converter that I use to translate from `throneteki-json-data` to `thronesdb-json-data` today. https://github.com/throneteki/throneteki-json-data/blob/master/src/ThronetekiToThronesDbConverter.js
