### ISSUE TITLE
Add icon house in Decklists (Mobile)

### ISSUE THREAD

**Issue by sergiqm94** [ThronesDB/thronesdb#327]
Add the faction house icon on the page "Decklists" mobile version. It would improve the user experience.

**Comment by stopfstedt** [comment]
current state:

![Selection_519](https://user-images.githubusercontent.com/1410427/58496514-e7dcd980-812e-11e9-9240-f7da02d952b3.png)

with house/agenda icons:

![Selection_520](https://user-images.githubusercontent.com/1410427/58496534-f1664180-812e-11e9-8e59-5a3b63e3747c.png)

alliance gets a bit long, but that's acceptable imo. 

![Selection_521](https://user-images.githubusercontent.com/1410427/58496614-12c72d80-812f-11e9-9d81-384e38801808.png)

**Comment by stopfstedt** [comment]
on second thought - showing _just_ the house, and _not_ the agenda(s) on mobile might be a better compromise.

![Selection_522](https://user-images.githubusercontent.com/1410427/58497764-8407e000-8131-11e9-947f-6b16ce83719b.png)

i think i'll move forward with that solution. @sergiqm94 thoughts/opinions?

**Comment by sergiqm94** [comment]
I think the first option would be better. In the case of the agenda "Alliance" do not show the other two Banners.

**Comment by stopfstedt** [comment]
> I think the first option would be better. In the case of the agenda "Alliance" do not show the other two Banners.

@sergiqm94 thanks for the feedback. i'll consider it. but also going to try to compress the layout for layout a bit, e.g. give more room to the images so they can appear side-by-side in mobile (for the first two). maybe we can fit everything in after all.

**Comment by stopfstedt** [comment]
@sergiqm94 i staged the changes on our sandbox server, can you do me a favor and give it a quick lookover on your mobile device? https://sandbox.thronesdb.com/decklists

thanks.

**Comment by sergiqm94** [comment]
Looks good

**Comment by stopfstedt** [comment]
thanks. i'll merge the code and roll this out with the june release.

**Comment by stopfstedt** [comment]
@sergiqm94 just the deployed this month's release, the changes are live on thronesdb. Cheers!
