### ISSUE TITLE
Suggestion: Add cycle icon on card preview

### ISSUE THREAD

**Issue by alaxmo13** [ThronesDB/thronesdb#329]
Currently when you are looking the card-preview window (the small one that appears when mouse is over a card name) you can read for example: Core Set #50 or King of Isles #35.

My suggestion is to change it for:

Core Set #50 (and the crown icon)
King of Isles #35 (and the kraken icon)

And the same for all cycles.

My idea is to easily find where a card belongs to one cycle or another with no need to know the chapter name.

Thanks!

**Comment by stopfstedt** [comment]
hey, thanks for making this suggestion. i would consider it, if i had the icon set for the cycles. which i don't, so i'll have to pass on this idea.
