### ISSUE TITLE
Numbers in list of expansions are wrong

### ISSUE THREAD

**Issue by Duckbringer** [ThronesDB/thronesdb#346]
![image](https://user-images.githubusercontent.com/34427714/62414007-bbee4080-b616-11e9-89a7-b707b6e60c31.png)

This is due to `<ol>` tag not being wrapped in `<li>` tag with title of the expansion.

correct would be:
```
<li>Westeros Cycle
<ol>
  <li>Taking the Black</li>
  ...
</ol>
</li>
```

**Comment by stopfstedt** [comment]
@Duckbringer nice catch! will push a fix for this out tonight.

**Comment by stopfstedt** [comment]
deployed to production. thanks for reporting!
