### ISSUE TITLE
Like and favorite buttons on decklists page doesn't work

### ISSUE THREAD

**Issue by fiskhandlarn** [ThronesDB/thronesdb#351]
Nothing happens when clicking on the like or favorite buttons alingside each deck on https://thronesdb.com/decklists. This is because the code for those buttons are in `ui.decklist.js`, which isn't included on https://thronesdb.com/decklists.

**Comment by stopfstedt** [comment]
thanks for reporting this. will look into it.

**Comment by fiskhandlarn** [comment]
I fixed it in my fork, I can make a PR tonight or tomorrow.

**Comment by stopfstedt** [comment]
superseded by #361
