### ISSUE TITLE
Disable comment link on deckslists page

### ISSUE THREAD

**Issue by fiskhandlarn** [ThronesDB/thronesdb#352]
The comment button next to each decklist on https://thronesdb.com/decklists is linked to https://thronesdb.com/decklists#comment-form (which only exists on individual decklist pages).

**Comment by stopfstedt** [comment]
rather than removing the link, i'll rewire this to take the user to the individual decklist page with focus set on the comments form. thanks for reporting.

**Comment by fiskhandlarn** [comment]
Good idea!

**Comment by stopfstedt** [comment]
i'm going to make this row of icons read-only everywhere but on the decklist details.  see #361
