### ISSUE TITLE
Is it an expected behaviour for the favorite button to also send like?

### ISSUE THREAD

**Issue by fiskhandlarn** [ThronesDB/thronesdb#353]
`src/AppBundle/Resources/public/js/ui.decklist.js`:

```js

    ui.send_favorite = function send_favorite(event)
    {

        // [...]

        ui.send_like.call($('.social .social-icon-like'), event);
    };
```

**Comment by fiskhandlarn** [comment]
And if so, shouldn't there be a way to retract one's like (as you can do with favorite)?

**Comment by stopfstedt** [comment]
i have to assume this was the original intent - if something is your "favorite", then you also must "like" it. on the surface, that logic checks out for me. but let me think about this some more, whether it make sense to decouple these or not. 

onto un-liking a list - that's something that should be possible. 

on a related note - every time a list receives a like, the list's author's reputation increases. for each 10 reputation points, a user receives an extra deck slot. if a like is removed, that author should not lose reputation from that.

**Comment by stopfstedt** [comment]
finally got around to fixing this, sorry that it took so long.
