### ISSUE TITLE
View as-dropdown does nothing for single cards

### ISSUE THREAD

**Issue by fiskhandlarn** [ThronesDB/thronesdb#355]
These show the same content:
- https://thronesdb.com/find?q=02006&sort=set&view=list
- https://thronesdb.com/find?q=02006&sort=set&view=spoiler
- https://thronesdb.com/find?q=02006&sort=set&view=card
- https://thronesdb.com/find?q=02006&sort=set&view=scan
- https://thronesdb.com/find?q=02006&sort=set&view=short

Should the dropdown be removed/disabled for single cards? If so the dropdown probably has to been shown again if the `smart-filter-help` input changes value though.

**Comment by stopfstedt** [comment]
for consistency reasons, i'd leave these controls in for all search results. will fix whatever needs fixing in order to make that work again.

@fiskhandlarn thanks for reporting, please keep 'em coming.

**Comment by fiskhandlarn** [comment]
Thank*you*! :) I've branched this delightful repo to make a builder for Doomtrooper. Almost there ...
