### ISSUE TITLE
Empty tags yields tag button with no content

### ISSUE THREAD

**Issue by fiskhandlarn** [ThronesDB/thronesdb#371]
If I remove all tags and put " " in the "Tags" input field, an empty tag button is shown on "My decks" page. I'm working on a fix.

**Comment by fiskhandlarn** [comment]
https://github.com/ThronesDB/thronesdb/pull/372

**Comment by stopfstedt** [comment]
hey, thanks for putting all this work in. will work my way through the PRs this week.

**Comment by stopfstedt** [comment]
fixed via #372
