### ISSUE TITLE
Sorting decks "by Set, then Number" echoes the set for each card

### ISSUE THREAD

**Issue by fiskhandlarn** [ThronesDB/thronesdb#377]
Sorting decks "by Set, then Number" shows the cards list with the set next to each card even though the set name is written as a headline above the cards. Shouldn't this sorting show a list similar to "by Set, then Name"?

**Comment by stopfstedt** [comment]
agreed, it's somewhat redundant to show the set title as a sub-heading, and then next to each card again. 
but then again, i get to reuse the templating function for sorting by "Faction, then Number". 
seems good enough the way it is right now.
