### ISSUE TITLE
Sorting decks "by Faction, then *" yields different types of info

### ISSUE THREAD

**Issue by fiskhandlarn** [ThronesDB/thronesdb#378]
Sorting decks "by Faction, then Name" doesn't show the sets but sorting "by Faction, then Number" shows the set names next to each card. Shouldn't these two sorts both show the set names?

**Comment by stopfstedt** [comment]
not really. the "Faction, then Number" option is really only there to provide some support for players that organize their collection by faction and in release order.
If you're organizing your collection by faction and card name, you won't need that additional info.
