### ISSUE TITLE
use non-incrementable identifiers for deck URLs

### ISSUE THREAD

**Issue by stopfstedt** [ThronesDB/thronesdb#383]
instead of the currently used sequentially created internal primary identifiers. 

this should curb attempts to scrape lists via script by incrementing the deck identifiers.

rig up a GUID generator and rework the routes/controllers accordingly. 

will require schema changes, too. 

back-fill existing lists via a custom Migration or command. 

apparently, the l5r db has this feature already, so see if this can be ported for starters.

**Comment by luky92** [comment]
just a suggestion to use the same links and have a password to access the list +plus whitelist 4 people who have access without password

**Comment by stopfstedt** [comment]
@luky92 interesting idea. i've been thinking along the lines of letting deck builders create/revoke shareable links, similar to how several google applications do it. but that's a follow-up item, let's squish the problem at hand first.
