### ISSUE TITLE
Card Tracker

### ISSUE THREAD

**Issue by Everr** [ThronesDB/thronesdb#44]
On Ringsdb.com, you have the ability to tick off packs you own and how many cores.
This makes it a lot easier to see what you're missing and also comes through when deckbuilding.
Would be a great feature for thronesdb as well.

**Comment by Alsciende** [comment]
That's awesome. I agree that ThronesDB should definitely have this feature.

**Comment by nilblank** [comment]
Love the idea of this feature.

**Comment by Hackmodford** [comment]
Came here to request this feature 👍

**Comment by stopfstedt** [comment]
superseded by #330. will talk a stab at it after Nats, this fall.
