### ISSUE TITLE
cannot start local server

### ISSUE THREAD

**Issue by marek-jasovsky** [ThronesDB/thronesdb#611]
good morning.

I have performed all the steps to import the data and create the superuser, but I am unable to start the server
code does not seem to contain namespace "server", neither any Command sets this name

many thanks

d:\Devel\ThronesDB\Master>php bin/console server:run

  There are no commands defined in the "server" namespace.

  Did you mean one of these?
      app:oauth-server
      app:oauth-server:client
      fos:oauth-server

**Comment by stopfstedt** [comment]
good catch. this is leftover from an earlier version of symfony and doesn't work with the currently used version (4) anymore. i'll remove it from the docs. 
you can try to spin the site up using the [symfony server](https://symfony.com/doc/4.4/setup/symfony_server.html) (i haven't tried that), or just run it the traditional way via apache, nginx etc.
