### ISSUE TITLE
unable to log in... "Invalid credentials" they say...  :(

### ISSUE THREAD

**Issue by PMMad** [ThronesDB/thronesdb#712]
Hi, for quite a while, each time I have tried to log myself in, I received this message: "Invalid credential". 

So far my only solution has been to reset my password and then log in right after, but it only works once, and then the next time I come back, it is that message again... 

Thanks !

(username: Mad')

**Comment by stopfstedt** [comment]
Hey @PMMad - turns out that the single quote in your username was causing issues. i removed it, please try again with just username `Mad`. 
Thanks!

**Comment by PMMad** [comment]
Hi Stefan,

Thanks for your answer and for fixing my problem !

With all my password changes, everypassword I have used has started to get
mixed in my head, so I'll reset it once for all and I'll keep that one.

Many thanks again !

Cheers!

Mad

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le sam. 9 janv. 2021 à 23:20, Stefan Topfstedt <notifications@github.com> a
écrit :
