### ISSUE TITLE
add "Work in progress" indicators to cards

### ISSUE THREAD

**Issue by stopfstedt** [ThronesDB/thronesdb#716]
add a flag at the pack-level. this will allow us to load cards that are "under constructions" and label them as such.

**Comment by ystros** [comment]
Is this something that should also live in the data repo? Could be an opportunity to consolidate the main repo and the Design Team's fork - assuming they don't want to keep the upcoming cards secret. (I'm guessing they don't care about if this feature will be implemented on ThronesDB to show off WIP cards)

**Comment by stopfstedt** [comment]
> Is this something that should also live in the data repo?

That would be even better, I assume your side of things could use this info as well.

> Is this something that should also live in the data repo? Could be an opportunity to consolidate the main repo and the Design Team's fork 

@ystros - agreed, that would be logical next step. I'll loop in Lukas when I file companion-tickets to this in the data repos.
