### ISSUE TITLE
Incorrect cost for 'Brimstone'

### ISSUE THREAD

**Issue by Patane97** [ThronesDB/thronesdb#719]
The cost for Brimstone within the deck editor has a gold value of 1 when it should be 2. The gold value of Brimstone on the card page is correct, issue only found in editor.
![Screenshot_20210218-133314_Edge](https://user-images.githubusercontent.com/23492047/108296760-3af19c80-71ee-11eb-8abd-830d2bb96d99.jpg)

**Comment by stopfstedt** [comment]
Hi @Patane97 , thanks for reporting this. You're coming up against an already fixed bug (see https://github.com/throneteki/throneteki-json-data/issues/99), but your browser must still be holding on to the old, incorrect cards data. 

Please try to clear your browser's cache and/or reload the page using your browser in a "private" tab, this should set things right again.
