### ISSUE TITLE
Add Affiliation to Text File and Markdown Exports

### ISSUE THREAD

**Issue by davidagnome** [ThronesDB/thronesdb#868]
When exporting or printing decklists, some players organize cards by affiliation instead of cycle/pack. The affiliation color icons in the HTML don't display in color when printing the decklist page in Chrome either.
```
---- Core Set ----
3x Littlefinger (Core Set #28 / Neutral)
1x Tyrion Lannister (Core Set #89 / Lannister)
```

**Comment by stopfstedt** [comment]
hey @davidagnome - i can't bolt additional info onto the text export, as this would break the import functionality with theironthrone, which is the primary use case for this feature at the moment. 

suggesting that if you must sort by affiliation that you use either the "sort by faction, then name" or "sort by faction, then number" option under "Actions". 

![image](https://user-images.githubusercontent.com/1410427/189687228-9ba1744e-42c3-4d0b-aa8e-c9145047f3d3.png)

from there, you can copy/paste or print your list. 

i'll change the print style sheet to respect colors though.

**Comment by davidagnome** [comment]
Here's an alternative, using print queries to add the value after the icon, which will help with color sight-impairments:
`@media print {
	.icon::after {
	    font-family: system-ui, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
	}

	.icon.fg-tyrell::after {
	    content: "(Tyrell)";
	}

	.icon.fg-targaryen::after {
	    content: "(Targaryen)";
	}

	.icon.fg-neutral::after {
	    content: "(Neutral)";
	}

	.icon.fg-greyjoy::after {
	    content: "(Greyjoy)";
	}

	.icon.fg-lannister::after {
	    content: "(Lannister)";
	}

	.icon.fg-thenightswatch::after {
	    content: "(The Night's Watch)";
	}

	.icon.fg-martell::after {
	    content: "(Martell)";
	}

	.icon.fg-stark::after {
	    content: "(Stark)";
	}
}`

**Comment by davidagnome** [comment]
Pull request #873 solves this through pure CSS. Huzzah!

**Comment by stopfstedt** [comment]
deployed. thanks again @davidagnome !
