### ISSUE TITLE
Fix "Keywords" section in "Rules Reference" page

### ISSUE THREAD

**Issue by LaranSoft** [ThronesDB/thronesdb#921]
In the "Keywords" section, in the "Rules Reference" page, there is a little inconsistency.

The third bullet point states:

"The keywords in the game are: ambush (X), assault, bestow (X), insight, intimidate, limited, no attachments, pillage, renown, shadow (X), stealth, and terminal."

and follows a sequence of "Related" links to said keywords.

Inconsistencies:

1) Keywords "Assault", "Bestow X", "Shadow X" are not listed in the "Related" section 
2) Keyword "Prized" is listed in the "Related" section but is not mentioned in the third bullet point, with the list of all keywords.

**Comment by stopfstedt** [comment]
Thanks for reporting. Fixed. Please see https://thronesdb.com/rulesreference#Keywords

**Comment by LaranSoft** [comment]
Thank you very much! Fix confirmed ;)
